"""Create liabilities table

Revision ID: 009b96f6cdbd
Revises: 04fac40350ab
Create Date: 2026-07-20 11:12:50.597329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009b96f6cdbd'
down_revision = '04fac40350ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('liability_type', sa.String(length=30), nullable=False),
    sa.Column('lender', sa.String(length=120), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('minimum_payment', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liabilities_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liabilities_user_id'))

    op.drop_table('liabilities')
    # ### end Alembic commands ###
