"""Link transactions to liabilities

Revision ID: 99831f305bc3
Revises: 009b96f6cdbd
Create Date: 2026-07-20 17:32:54.908947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99831f305bc3'
down_revision = '009b96f6cdbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "liability_id",
                sa.Integer(),
                nullable=True,
            )
        )

        batch_op.create_index(
            batch_op.f("ix_transactions_liability_id"),
            ["liability_id"],
            unique=False,
        )

        batch_op.create_foreign_key(
            "fk_transactions_liability_id",
            "liabilities",
            ["liability_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_transactions_liability_id",
            type_="foreignkey",
        )

        batch_op.drop_index(
            batch_op.f("ix_transactions_liability_id")
        )

        batch_op.drop_column("liability_id")

    # ### end Alembic commands ###
